title:  Alexander G. Lopez
description: My Open Source Learnings
theme:      null      # we’re rolling our own
plugins:    []        # no extra bells & whistles
markdown:   kramdown  # default
highlighter: rouge    # for code syntax highlighting

kramdown:
  input: GFM
  syntax_highlighter: rouge
